services:
  catalog-svc:
    image: hnrkjnsn/catalog-svc:opg1401
    hostname: catalog-svc01
    build:
      context: ../catalog
      dockerfile: Dockerfile
    environment:
      - CatalogImagePath=/srv/resources/images
      - MongoConnectionString=mongodb://root:rootpassword@mongodb:27017/?authSource=admin
      - CatalogDatabase=catalog
      - CatalogCollection=products
      - GatewayUrl=http://gateway:4000
    expose:
      - "8080"
    depends_on:
      - mongodb
    volumes:
      - catalog-images-volume:/srv/resources/images
    networks:
      - foodnet

  nginx:
    image: nginx:latest
    container_name: "gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/srv/www/data
    depends_on:
      - catalog-svc
    ports:
      - "4000:4000"
    networks:
      - foodnet

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - foodnet

networks:
  foodnet:
    driver: bridge

volumes:
  mongodb_data_container:
  catalog-images-volume:
    external: false